db: './db'

model:
  name: 'Dolphin'
  base_url: 'http://localhost:11434'
  temperature: 0
  num_ctx: 8192
  num_predict: 1536

history_size: 6

embedder: 'embed-multilingual-v3.0'
reranker: 'rerank-multilingual-v3.0'

retrieval_threshold: 0.6 # Si usa dopo ogni compressione
followup_threshold: 0.35 # Si usa per i documenti di followup
distance_threshold: 0.25 # Si usa per la vector distance
simplifier: 0.5 # Si usa nella similarity dopo la prima compressione

k: 14 # standard retriever documents
top_n: 6 # compressor documents

graph_verbose: True